### ISSUE TITLE
Unable to build on Windows 8.1 and VS 2013

### ISSUE THREAD

**Issue by anweiss** [fuwaneko/node-protobuf#27]
Getting numerous errors when building on Windows 8.1 using Visual Studio 2013. Followed README steps to compile libprotobuf.lib but receive the following errors when executing `npm install node-protobuf` (errors below are a snippet of all errors shown in console):

```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used,
 but unwind semantics are not enabled. Specify /EHsc [C:\Users\anweiss\Documents\Development\testthinky\node_modules\no
de-protobuf\build\protobuf.vcxproj]
..\protobuf.cpp(34): error C2039: 'FunctionCallbackInfo' : is not a member of 'v8' [C:\Users\anweiss\Documents\Developm
ent\testthinky\node_modules\node-protobuf\build\protobuf.vcxproj]
..\protobuf.cpp(34): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\User
s\anweiss\Documents\Development\testthinky\node_modules\node-protobuf\build\protobuf.vcxproj]
..\protobuf.cpp(34): error C2143: syntax error : missing ',' before '<' 
```
